# -*- coding: utf-8 -*-
"""FASTAPI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GawtxHzSZ7tPvRwDx0hYwGRy97TW33it
"""

from fastapi import FASTapi

app = FastAPI()

@app.get("/")
async def root():
    return {"message": "Hello World"}